### ISSUE TITLE
Incorrect extraction of diffstat

### ISSUE THREAD

**Issue by bonzini** [patchew-project/patchew#114]
https://patchew.org/QEMU/20190325155923.30987-1-pbonzini@redhat.com/

**Comment by bonzini** [comment]
Patch posted.

**Comment by bonzini** [comment]
Ironically, the patchew page for [this patch](https://patchew.org/Patchew/20190416214912.31547-1-pbonzini@redhat.com/) shows another bug in diffstat extraction. My first version of the patch also bailed out at lines starting with "diff", but I was afraid that this could have false positives in the commit message. Maybe we could bail at "diff" if a diffstat was found before (i.e. `ret != []`).

We could also require a "---" line before the diffstat, but there are people that are using e.g. quilt instead of `git format-patch` and do not include such a line. Overall the remaining case seems like a minor issue.

**Comment by famz** [comment]
Maybe two consequent lines
```
diff ...
index ...
```
is better?

**Comment by bonzini** [comment]
`---` is simpler and even better for avoiding false positives.

**Comment by bonzini** [comment]
I mean stopping at ---.

**Comment by bonzini** [comment]
Pushed to next.patchew.org just to see what it looks like, everything seems okay:

* http://next.patchew.org/Patchew/20190416214912.31547-1-pbonzini@redhat.com/
* http://next.patchew.org/QEMU/20190325155923.30987-1-pbonzini@redhat.com/
