### ISSUE TITLE
How does tester work?

### ISSUE THREAD

**Issue by liuw** [patchew-project/patchew#115]
Hi Paolo and others

We in Xen project want to add a bot that pulls patches from xen-devel and triggers CI loop. Patchew seems to fit this role perfectly.

I had a look at the emails sent by patchew for QEMU. It is clear to me that those scripts aren't part of the patchew repository.

Unfortunately the doc is a bit lacking. Can you tell me how the tester framework / module is supposed to work? 

Wei.

**Comment by bonzini** [comment]
Hi! The tester is installed with ansible just like importer and server. It polls the server for patches to test and runs a script. It. We plan to configure everything by YAML in the future, for now the script can be configured with a web GUI.

The QEMU setup _would_ look like [https://patchwork.kernel.org/patch/10854385/](this) in YAML. If you open http://patchew.org/ProjectName/info while logged in, it should be easy to figure out the conversion from YAML to the web GUI.

**Comment by liuw** [comment]
Thanks Paolo. I will check out those links.
