### ISSUE TITLE
Request to host Xen project

### ISSUE THREAD

**Issue by liuw** [patchew-project/patchew#116]
Hi

I would like to make a request to host Xen hypervisor development list on patchew.org. Thanks for your consideration.

Thanks,
Wei

**Comment by famz** [comment]
Could you provide the url to list info pages?

**Comment by liuw** [comment]
The info page is at https://lists.xenproject.org/mailman/listinfo/xen-devel .

**Comment by famz** [comment]
Something is wrong: ERR_CONNECTION_TIMED_OUT when I hit subscribe button there..

**Comment by liuw** [comment]
I just tried subscribing with my personal email address. It worked. There could be a hipccup. Can you try again?

**Comment by famz** [comment]
Done

New patches will show up here:

https://patchew.org/Xen/

Will you be interested in enabling tests for Xen as well?

**Comment by liuw** [comment]
Thank you!

Yes I'm interested in enable tests for Xen as well.

**Comment by bonzini** [comment]
Do you already have a script that e.g. starts a VM with the hypervisor you've just built and runs the tests?

**Comment by liuw** [comment]
Hi Paolo. Fam has enabled testing for me. I am trying to figure out how to best integrate patchew with existing infrastructure.
