### ISSUE TITLE
New EDK2 mailing list

### ISSUE THREAD

**Issue by bonzini** [patchew-project/patchew#118]
New EDK2 mailing list is at devel@edk2.groups.io.  Fam, can you subscribe to it both importers, and unsubscribe from  edk2-devel@lists.01.org?

**Comment by bonzini** [comment]
Because of #117 I have added the mailing list manually via the Django shell. Let's see if everything works.

**Comment by famz** [comment]
Cool, thanks!

**Comment by bonzini** [comment]
Patches are fetched nicely but they are not applied, probably because of the CR/LF mess that is edk2. I'll ask Laszlo.
