### ISSUE TITLE
EDITOR variable at /scripts/deploy-tester isn't working on Fedora 24 x86_64

### ISSUE THREAD

**Issue by ramonmedeiros** [patchew-project/patchew#12]
When doing my setup, got issue at line 40 in /scripts/deploy-tester. The issue was an empty var EDITOR. Not sure if this one is correctly set on my profile or bashrc, but would be nice to see /etc/alternatives (i guess)

**Comment by famz** [comment]
Fixed by commit baefd3dcd70579c4fc8499815dcb350412817439.
