### ISSUE TITLE
patch with only file renamings "is not received"

### ISSUE THREAD

**Issue by senya** [patchew-project/patchew#131]
HI all!

Look at my series https://patchew.org/QEMU/20210109122631.167314-1-vsementsov@virtuozzo.com/

Patchew marks it as incomplete, as " Only 10 patches received!". Actually, patch 11 _is_ received, and shown on series page (see the link).. But may be it's not recognized as patch? The problem is reproduced also in a previous (v5) version of the series.

**Comment by famz** [comment]
Thanks, I will fix it.

**Comment by famz** [comment]
Proposed patch: https://patchew.org/Patchew/20210109205958.1096197-1-fam@euphon.net/

**Comment by senya** [comment]
Thanks a lot for fast fix!
