### ISSUE TITLE
Change git repo for Kimchi

### ISSUE THREAD

**Issue by ramonmedeiros** [patchew-project/patchew#14]
Hi,

please, change Kimchi repository to:

https://github.com/kimchi-project/wok.git

**Comment by famz** [comment]
But there is a also "Wok" project now, should I delete it?

**Comment by ramonmedeiros** [comment]
Nop. I will try to handle git submodules dependencies this way

**Comment by famz** [comment]
Changed: http://patchew.org/Kimchi/info
