### ISSUE TITLE
shutil.rmtree cannot deal with file permissions

### ISSUE THREAD

**Issue by ramonmedeiros** [patchew-project/patchew#18]
at patchew-cli:

455                     log = "N/A. Internal error while reading log file\n"
456                 print("  Result:", "Passed" if passed else "Failed")
457                 logging.debug(log)
458                 self.api_do("testing-report", project=r["project"],
459                                               identity=r["identity"],
460                                               test=r["test"]["name"],
461                                               tester=args.name,
462                                               head=r["head"],
463                                               base=r["base"],
464                                               passed=passed,
465                                               log=log,
466                                               is_timeout=is_timeout)
467                 logf.close()
468             finally:
469                 shutil.rmtree(wd)
470             return True

shutil.rmtree does not deal with files generate by root. I'm not sure how to deal with this issue, since running patchew with sudo is ugly. As workaround, i add a line to change file permissions. 

I have no propose at this moment to fix this in a good way.

**Comment by famz** [comment]
If the test script created these files, it probably makes more sense if they get cleaned up there before the script exits. I cannot think of a good way here either..
