### ISSUE TITLE
Simplify series view

### ISSUE THREAD

**Issue by bonzini** [patchew-project/patchew#22]
Simplify series view to avoid having to fold or expand the panes. For example:

* show all tests in a single pane, with links to the logs; if Javascript is enabled, the logs can open in a modal view

* show all message subjects in a single pane, with links to a separate view that shows the diff on top in a graphical manner, and then the replies afterwards - maybe show different icons for messages that had replies

**Comment by bonzini** [comment]
... in fact I am thinking of adding "results" (of applying, testing, etc.) to the database as a first-class entity instead of using properties.

It would be similar to GitHub statuses, see [here](https://developer.github.com/v3/repos/statuses/).

**Comment by bonzini** [comment]
Some work on this is at [bonzini/new-series-detail](https://github.com/bonzini/patchew/compare/hackable...bonzini:new-series-detail) (and here are [pictures](https://imgur.com/a/fCkpo)). Of course this is using the current DB schema. :)

Let's first merge PR  #21 though.

**Comment by famz** [comment]
Looks very nice! Can we top-align the two columns at the end (The "Expand all" menu on the left and the message panels on the right) ?

**Comment by bonzini** [comment]
This is still a work in progress. The idea is to move extra ops to a floating box on the top section, and change expand/collapse to a horizontal menu... Maybe tomorrow or next week though.

**Comment by bonzini** [comment]
See pull request #41 for a first part.
