### ISSUE TITLE
Improve cross-series diff

### ISSUE THREAD

**Issue by bonzini** [patchew-project/patchew#23]
Take inspiration from [git-tbdiff](https://raw.githubusercontent.com/trast/tbdiff/master/git-tbdiff.py) to match each patch to the same patch (hopefully) in the previous version.

**Comment by bonzini** [comment]
Fam, I would like to work on this next. Do you think the heavy-weight computations should be done in Python or Javascript? The cross-series diff is already done in Javascript, so perhaps it should all be on the client-side.

(Python uses C code for the matching algorithm, but [it](https://github.com/bonzini/hungarian-algorithm-n3/blob/master/hungarian.c) shouldn't be hard to convert it to Javascript).

**Comment by famz** [comment]
I think Python is the easier way? I assume it shouldn't add much more load to the server. the worse case is to cache the results or even offload the task to appliers. And the advantage is that we can easily make it available in patchew-cli too.

On the other hand if you prefer JS and think it is easy to maintain, I won't object.

**Comment by bonzini** [comment]
> the advantage is that we can easily make it available in patchew-cli too

That's an interesting point.

On the other hand, this would also need a python diff lib, so we'd have to move diffing and "diff opcode" generation to Python to do it in patchew-cli. I found a Hungarian algorithm [implementation in Javascript](https://github.com/addaleax/munkres-js), so it seems much easier to go for Javascript.

**Comment by famz** [comment]
> so it seems much easier to go for Javascript.

Sounds good to me.

**Comment by bonzini** [comment]
See pull request #42  for a first part.

**Comment by bonzini** [comment]
Once we have a single-patch view (#22), the next part could be to link each git-tbdiff header to it, on both sides. This way the user can click the left side and check what remarks were made, for example.
