### ISSUE TITLE
Deploy a test server running the latest version of patchew

### ISSUE THREAD

**Issue by bonzini** [patchew-project/patchew#24]

**Comment by famz** [comment]
The idea is: besides the main patchew.org site, we can deploy a mirror that runs slightly newer code (e.g. from a "next" branch) on next.patchew.org; the mirror can then be used to test out changes without impacts to the main service users and projects.

Ideally everything in the main site's DB should be mirrored but the email notification will be limited to subscribers only. What is the best way to implement this is still not clear, though.

**Comment by bonzini** [comment]
I think even a completely new instance (initialized with the old DB data, or with a minimal set of patches just to have something to show) would be enough.

**Comment by famz** [comment]
What are tricky to test locally (auto or manual) are the specifical things in the "live" patchew.org. I think they are basically the interactions between importers, testers, the server itself and the SMTP service, with real data. So we may also deploy a copy of "importer", a simple tester that perhaps fails randomly ;-), just to allow the new instance to exercise more code..

**Comment by bonzini** [comment]
- [x] next.patchew.org is up,
- [ ] auto-deploy every 24 hours or every commit
- [ ] add importer to next.patchew.org
- [ ] add tester to next.patchew.org
