### ISSUE TITLE
Patchew did not match "Reviewed-By" when "Tested-By' is together

### ISSUE THREAD

**Issue by ramonmedeiros** [patchew-project/patchew#3]
Hi,

i notice that patchew add an R icon to reviewed patches, but, in a patch that has Reviewed-By, it can't add it. Maybe it's an issue with regexp. Here is the email:

http://lists.ovirt.org/pipermail/kimchi-devel/2016-April/014449.html

**Comment by famz** [comment]
Hi, Ramon, sorry for the late reply. I think this is the current limitation of case sensitive match. Will update to case-insensitive in the new version. Thanks.

**Comment by famz** [comment]
Fixed since 0573c6c
