### ISSUE TITLE
Duplicated test run and report

### ISSUE THREAD

**Issue by famz** [patchew-project/patchew#63]
With the current test dispatching logic, two or more testers can get the same task and both report success/failure. Upon failure, two events are generated, as a result, two email reports can be sent:

https://lists.gnu.org/archive/html/qemu-devel/2018-03/msg00279.html

**Comment by bonzini** [comment]
Should be fixed, or at least mitigated, by commit 0a17dcd1ef9f12e39fd51b86d4e931cf11622177 ("testing: do not restart jobs too soon").
