### ISSUE TITLE
Should maintainers have access to git configuration?

### ISSUE THREAD

**Issue by bonzini** [patchew-project/patchew#66]
Currently, `mods/git.py` only shows the config box to superusers:

    def prepare_project_hook(self, request, project):
        if not request.user.is_superuser:
            return
        project.extra_info.append({"title": "Git configuration",
                                   "class": "info",
                                   "content_html": self.build_config_html(request,
                                                                          project)})

Is this intended?

**Comment by bonzini** [comment]
FWIW I added the docs tag because this is (somewhat) blocking the creation of documentation - you cannot really have per-project maintainers until this is fixed.

**Comment by famz** [comment]
Good point. Overall I think maintainer code could use quite some renovation. Adding the docs tag back.

**Comment by bonzini** [comment]
Fixed by commits f845f6359ae939d72c40db46710d676755944b0a and (sorry for rushing) f020fcdf1e95ab3f19a9f19e3ea9c3de1c7623fe.
