### ISSUE TITLE
Should "Download mbox" only include the original patches?

### ISSUE THREAD

**Issue by bonzini** [patchew-project/patchew#7]
Currently, the "Download mbox" link includes the whole thread for a patch series. It would be interesting to include only the patches with the tags (i.e. Reviewed-by/Tested-by) already in place. This way one could "curl ... | git am -3 -s" from the "Download mbox" to apply a patch.

**Comment by famz** [comment]
Including only the patches in "Download mbox" is reasonable, but I'm not sure about mixing the "tags" in (in other words manipulating the body).

How about using patchew-cli (it only depends on standard python modules, and talks to patchew.org using patchew JSON API)?

```
curl https://raw.githubusercontent.com/patchew-project/patchew/master/patchew-cli > \
  $HOME/bin/patchew
chmod +x $HOME/bin/patchew
cd $QEMU_SRC
patchew apply id:1471596663-31298-1-git-send-email-felipe@nutanix.com
```

The `id:xxx` part can be copy-pasted from the search bar in the "Download mbox" page, if you are using the web. (BTW patchew-cli has search command too).

I just added a "--signoff (-s)" option to the apply subcommand so it can behave like "git am -s".
