### ISSUE TITLE
mods/testing.py "testers" and "users" unused?

### ISSUE THREAD

**Issue by bonzini** [patchew-project/patchew#72]
`_find_applicable_test` does this:

            if t.get("tester") and tester != t["tester"]:
                continue
            if t.get("user") and user.username != t["user"]:
                continue

As far as I understand, the "tester" and "user" keys are not going to be there unless they're added manually through the admin site, because the schema has "testers" and "users" instead. Should these four lines be fixed (something like `tester in t["testers"].split(",")` or removed?

**Comment by famz** [comment]
Aha, good catch. For once I tried this feature one patchew.org and wondered why it didn't work as expected. :)

Let's drop this feature (including the schema) altogether. It's unused, broken, and I find it can be fully achieved with capabilities filtering.
