### ISSUE TITLE
HSTS (automatically redirect to HTTPS) for patchew.org

### ISSUE THREAD

**Issue by bonzini** [patchew-project/patchew#89]
HSTS is an HTTP header that informs a browser that all future connections to a particular site should always use HTTPS. Combined with redirecting requests over HTTP to HTTPS, this will ensure that connections always enjoy the added security of SSL provided one successful connection has occurred. HSTS may either be configured with SECURE_HSTS_SECONDS, SECURE_HSTS_INCLUDE_SUBDOMAINS, and SECURE_HSTS_PRELOAD, or on the Web server.

**Comment by famz** [comment]
Good idea, I've configured HSTS and redirect on the patchew.org server.

**Comment by bonzini** [comment]
HSTS is not configured right now.

**Comment by bonzini** [comment]
Fixed.

    $ curl -I http://patchew.org/QEMU/
    HTTP/1.1 301 Moved Permanently
    Server: nginx/1.12.2
    Date: Mon, 18 Mar 2019 09:00:50 GMT
    Content-Type: text/html
    Content-Length: 185
    Connection: keep-alive
    Location: https://patchew.org/QEMU/
    Strict-Transport-Security: max-age=31536000
