### ISSUE TITLE
Sanitize or prevent the crawling of mbox files by search engines

### ISSUE THREAD

**Issue by pageflt** [patchew-project/patchew#94]
The mbox files associated with patch series are being crawled by search engines. As consequence, contributors' e-mail addresses and names are being tied to the public IP addresses of the networks they sent their patches from, which is undesirable and a major privacy concern.

Can you please address this issue by either stripping/sanitizing the e-mail headers, or by preventing the indexing of mbox files by search engines?

As an example of the issue, you can perform a Google search for "qemu site:patchew.org inurl:/mbox".

**Comment by bonzini** [comment]
Everybody can get the information just by downloading the mailing list archives (see for example ftp://lists.gnu.org/qemu-devel/) or subscribing to the mailing list.

IP addresses where you send email from is public information, and anybody who is concerned of their privacy _and_ is sending email to a public mailing list should be aware of that.
